services:
  database:
    container_name: full-stack-app-database
    image: postgres:15.1
    environment:
      POSTGRES_DB: customer
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1478236950
      PGDATA: /data/postgres
    volumes:
      - database:/data/postgres
    ports:
      - "5433:5432"
    networks:
      - database
    restart: unless-stopped
  full-stack-app-backend:
    container_name: full-stack-app-backend
    image: kolyakhryapov/full-stack-app-backend
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://database:5432/customer
    ports:
      - "8080:8081"
    networks:
      - database
    depends_on:
      - database
    restart: unless-stopped
  full-stack-app-frontend:
    container_name: full-stack-app-frontend
    image: kolyakhryapov/full-stack-app-frontend
    build:
      context: frontend/vite-project
    ports:
      - "3000:5173"
    depends_on:
      - full-stack-app-backend
    restart: unless-stopped

networks:
  database:
    driver: bridge

volumes:
  database:
