server:
  port: 8081
  error:
    include-message: always

cors:
  allowed-origins: "*"
  allowed-methods: "*"
  allowed-headers: "*"
  exposed-headers: "*"

spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/customer
    username: postgres
    password: 1478236950
  jpa:
    hibernate:
      ddl:auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: false
  main:
    web-application-type: servlet
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  codec:
    max-in-memory-size: 10MB

file-storage:
  profile-image-directory: "backend/src/main/resources/static/images/user-%s/profile-image/"
  profile-image-name: "%s-profile-image%s"